### ISSUE TITLE
What's the prescribed way to `docker login` before `dusty up`?

### ISSUE THREAD

**Issue by mugli** [gamechanger/dusty#626]
First time `dusty up` fails if it needs to pull private docker images but is not logged in to docker registry. I'm trying to document the steps for the team and confused about how to proceed without facing the error. It feels not so ok to tell everyone that *it'll fail but move on*.

I've tried `docker-machine start dusty && docker login` before `dusty up`, but before first time initialization (`dusty up`) the docker-machine isn't even ready.

Should there be a `dusty login` command that dusty will handle login without exposing the users to docker-machine? 

Or, should dusty initialize the VM and docker-machine (and also export the environment variables by `eval "$(docker-machine env dusty)"`) even before the first time `dusty up` command, maybe during installation?

Is there any other way to solve this?

**Comment by thieman** [comment]
Dusty doesn't currently provide any utilities for private registries requiring login. I'll look into this a bit in the next few days and see if I can come up with a good way to bring in support, there is likely something we can do in the VM layer to make this fairly painless.

**Comment by thieman** [comment]
@paetling @mugli My understanding is that `docker login` and the associated pulls of images from private registries are all controlled by the client config file, which by default is located at `~/.docker/config.json`. Here's an example of what mine looks like after I log in to the public reg:

```
{
        "auths": {
                "https://index.docker.io/v1/": {
                        "auth": "REDACTED",
                        "email": "travis.thieman@gmail.com"
                }
        },
        "HttpHeaders": {
                "User-Agent": "Docker-Client/1.10.0 (darwin)"
        }
}
```

At `pull` time, all authentication is based off of this file, the `login` command itself just populates this if it gets a successful response on the login attempt. The daemon isn't saving the login state, it just reads from this file every time you try to pull.

My current thinking is to add a `login_required` boolean key to app, service, and test specifications (anywhere you can define an image) that would mark an image as requiring login. If this is set to `True`, Dusty can check the client config at `up` time and abort if it detects any required registries do not currently have any login information. We could then present the user a fairly targeted error message telling them how to fix them problem, e.g. `Not authenticated to private registry, run docker login <registry host> to correct`. We could do this abort at the same time we abort on not having required assets, so the user doesn't have to wait long for the `up` to error out.

Does that sound like an agreeable solution?

**Comment by thieman** [comment]
On second thought, we've had problems with making new users run `docker` commands themselves because Machine requires you to run the `eval $(docker-machine env dusty)` incantation before you can run anything. Maybe it is actually worth stepping them through it. Probably not too hard, we would just need to put an interrupt point into the `up` flow to give control back to the Dusty client from the daemon.

**Comment by paetling** [comment]
I like the overall idea of helping with login.  I like the second implementation suggestion better for a few reasons:
1. The eval flow you mentioned
2. If we can recognize there is an error, it seems pretty simple to help fix that error.  Instead of forcing a user out of the dusty flow
3. I like idea of moving dusty forward as your one stop shop for local docker work. So users who do not really care about what their local env is or how docker works do not need to use multiple systems to make this work

How do you see the login required method working.  If a .yml file has login required, we check the config.json file to see if there is a config for the start_path of an image name?  If an image name is `docker.yourcompany.com` but the image name is `docker.yourcompany.com/this/is/the/name` how do you figure out the registry?  Can they only be the info before the slash?  If not, we might need that key to actually specify the required registry.

**Comment by thieman** [comment]
@mugli We just pushed a release candidate `0.6.6-RC2` with our solution for the issue, PR is here: #641.

We don't have any private registries which require auth to test against, so it'd be great if you could download the RC and let us know if it works for your use case. All you should need to do is upgrade your Dusty:

```
dusty upgrade 0.6.6-RC2
```

And then add `image_requires_login: True` to any specs specifying an image on your private registry. If you want to test how it behaves when a user has not yet authed, you can blow away your client config at `~/.docker/config.json`

**Comment by mugli** [comment]
I did this:

- Upgraded dusty `dusty upgrade 0.6.6-RC2`
- Stopped dusty vm (mainly to mimic first time `dusty up` scenario) `docker-machine stop dusty`
- Removed client config `rm ~/.docker/config.json`
- Added `image_requires_login: True` to app configs
- Run `dusty up`

This time, as the dusty vm is stopped, `docker login` fails every time.

```
> dusty up
Pulling latest updates for all active managed repos:
Updating managed repos

Processing required login for index.docker.io
Username:
Password:
Email: 
Cannot connect to the Docker daemon. Is the docker daemon running on this host?

Login failed, please try again for index.docker.io (Ctrl-C to quit)
```

**Should `dusty up` start the vm first if it's not running?**

Then, I tried: 
- Start dusty vm manually `docker-machine start dusty`
- Make sure `docker-machine status dusty` shows `Running`
- Run `dusty up`

Dusty still cannot login as it cannot connect to docker daemon.

Then, I tried: 
- Run `eval "$(docker-machine env dusty)"`
- Run `dusty up`

Now login proceeds successfully!

**Should `dusty up` set docker-machine's env variables before trying to login?**

**Comment by mugli** [comment]
Also, this adds to list of differences in capabilities of apps and services #472

**Comment by thieman** [comment]
That's odd, I believe we are setting the right Docker envvars whenever we run any Docker subprocesses. Let me try to reproduce, thanks for helping us test.

**Comment by thieman** [comment]
Also you make a good point, since currently we do not have a custom service spec (and just use Compose's) the v1 of this feature isn't going to support services. This might be one reason we would consider moving to using our own service spec, even if we only add a couple of keys on top of Compose.

**Comment by mugli** [comment]
:+1: for dusty's own service spec. Apps config now feels way superior than compose spec, specially for host forwarding and this newly added support for private repositories.

**Comment by thieman** [comment]
@mugli Fixes pushed as `0.6.6-RC3` if you'd like to test again, sorry for that

**Comment by mugli** [comment]
I'm getting this error for now:
```
>> dusty up

Pulling latest updates for all active managed repos:
Updating managed repos
Starting docker-machine VM dusty

[__WAITS FOR A LONG TIME HERE__]

ssh: connect to host 10.174.249.15 port 22: Operation timed out
ERROR: Command 'ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /Users/mehdi/.docker/machine/machines/dusty/id_rsa docker@10.174.249.15 which rsync || tce-load -wi rsync || tce-load -wi rsync' returned non-zero exit status 255
```

Not sure if something is messed up with this machine. Will try again from work tomorrow.

**Comment by thieman** [comment]
Exit code 255 usually means there's a different problem, maybe check your logs at `/var/log/dusty.log` to see if Machine is giving you any more information. Does `docker-machine ssh dusty` work?

**Comment by thieman** [comment]
We just had someone here have the same problem using an older version of Machine (0.4.1), could you please report your Machine version and upgrade to latest 0.6 if possible? The person here was running into a known problem with VBox host-only interfaces which later Machine versions attempt to work around.

**Comment by mugli** [comment]
Upgraded docker-machine to latest 0.6, still the same problem.
`docker-machine ssh dusty` works.
I deleted `/var/log/dusty.log` to see fresh logs, but then it is not being created/updated again. :/

**Comment by thieman** [comment]
Okay, time to try a time-honored VBox unsticking method which we are probably gonna bake into a Dusty command soon because of how often people end up needing to do it. This blows away your VM, you might want to run `dusty disk backup` beforehand if you have persisted data you want to keep.

1. `docker-machine stop dusty && docker-machine rm dusty`
2. Open the VirtualBox GUI.
3. Go to VirtualBox -> Preferences -> Network -> Host-only Networks
4. Delete all the Host-only Networks.
5. Try `dusty up` again.

This is a known awful VBox problem that newer Machines try to work around, but I don't think they can work around it retroactively. Hope this resolves things for you.

**Comment by mugli** [comment]
Did all of the above. Then, this time:
```
>>> dusty up
Pulling latest updates for all active managed repos:
Updating managed repos
ERROR: Command '['docker-machine', 'create', '--driver', 'virtualbox', '--virtualbox-cpu-count', '-1', '--virtualbox-memory', '6144', '--virtualbox-hostonly-nictype', 'Am79C973', 'dusty']' returned non-zero exit status 1
```

Trying it again:
```
>>> dusty up
Pulling latest updates for all active managed repos:
Updating managed repos
Stopping Dusty VM to apply NIC fix for faster networking performance
Setting NIC 1 to use PCnet-FAST III
Starting docker-machine VM dusty

Processing required login for index.docker.io
Username:
Password:
Email: 

Login failed, please try again for index.docker.io (Ctrl-C to quit)
```

Trying to eval env vars manually, I think I should mention this:
```
>>> eval "$(docker-machine env dusty)"
Error checking TLS connection: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": x509: certificate is valid for 10.0.2.15, not 192.168.99.100
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which will stop running containers.
```

So, regenerate certs and try dusty up again:
```
>>> docker-machine regenerate-certs dusty
Regenerate TLS machine certs?  Warning: this is irreversible. (y/n): y
Regenerating TLS certificates
Waiting for SSH to be available...
Detecting the provisioner...
Copying certs to the local machine directory...
Copying certs to the remote machine...
Setting Docker configuration on the remote daemon...

>>> dusty up
Pulling latest updates for all active managed repos:
Updating managed repos

Processing required login for index.docker.io
Username:
Password:
Email: 
...
```

Working now! 🎉

**Comment by thieman** [comment]
Ugh. We saw a bunch of this internally yesterday when we had people upgrade their Docker Machine. For whatever reason, upgrading Machine seemed to make existing VMs very finicky. Hopefully it behaves now that you've gotten over the initial hurdle.

0.7.0 is released, be sure to grab it through `dusty upgrade`. Going to close this one for now.
